service: lambda-service

plugins:
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'image/png'
  runtime: nodejs14.x
  region: us-west-1

functions:
  image-generator:
    handler: src/handler.default
    events:
      - http:
          method: get
          path: '{proxy+}'
    environment:
      NODE_PATH: './:/opt/nodejs/node_modules'
      FONTCONFIG_PATH: '/var/task/fonts'
    layers:
      - arn:aws:lambda:us-west-1:501790583599:layer:canvas-nodejs:1

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
